
version: '3.4'

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  celery_service:
    image: celery_service
    container_name: celery_app
    depends_on:
      - redis
    hostname: celery

  app:
    image: flask_service
    container_name: flask_app
    depends_on:
      - redis
      - celery_service
    ports:
      - "4001:5001"
    hostname: app
