apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: flask-api
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-app
        image: mhausenblas/simpleservice:0.5.0
        ports:
        - containerPort: 9876
        env:
        - name: SIMPLE_SERVICE_VERSION
          value: "0.9"
