apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: userimack/flask_app:v1
        ports:
        - containerPort: 5000
        env:
        - name: MESSAGE
          value: "Hyderabad Python Group"

